spring:
  application:
    name: 'demo-application'
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: 'jdbc:h2:file:/C:/Temp/movies.db'
    username: 'sa'
    password:
    driverClassName: 'org.h2.Driver'
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update